# Generated by Django 4.1.5 on 2023-01-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Создано в: ')),
            ],
        ),
    ]
